Resources:
  AthenaDatabase:
    Type: AWS::Glue::Database
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Name: website_db	
        Description: Database to hold tables for flights data
        LocationUri: s3://${self:custom.streamBucket}/workshop

  AthenaTable:
    Type: AWS::Glue::Table
    DependsOn:
      - AthenaDatabase
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AthenaDatabase
      TableInput: 
        Name: website_clicks_tb
        Description: Table to hold clicks from users
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: csv
        PartitionKeys: 
          - Name: year
            Type: bigint
          - Name: month
            Type: bigint
          - Name: day
            Type: bigint
          - Name: hour
            Type: bigint
        # Retention: Integer
        StorageDescriptor: 
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Location: s3://${self:custom.streamBucket}/workshop
          Columns:
            - Name: usr
              Type: VARCHAR(128)
            - Name: ts
              Type: INT
            - Name: type
              Type: VARCHAR(128)
            - Name: x
              Type: TINYINT
            - Name: y
              Type: TINYINT
            - Name: toElement
              Type: VARCHAR(128)
          Compressed: True
          SerdeInfo:
            Parameters:
              "serialization.format": "1"
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
