Resources:
  WebAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
      - '-'
      - - ${self:custom.s3Bucket}
        - !Select
          - 0
          - !Split
            - '-'
            - !Select
              - 2
              - !Split
                - '/'
                - !Ref 'AWS::StackId'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  WebAppS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebAppS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
            - s3:GetObject
            Resource: !Join
              - ''
              - - !GetAtt WebAppS3Bucket.Arn
                - /*